name: Import API_KEY

on: [push]  # Trigger the workflow on pushes to any branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the virtual environment

    steps:
      - uses: actions/checkout@v3  # Checkout the repository's code

      - name: Set API_KEY environment variable securely
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
        env:
          API_KEY: ${{ secrets.API_KEY }}  # Set as a job-level environment variable
